title: Aybarinee Campbell Mendez
logo: /assets/img/headshot_circle.PNG
description: Resume and Portfolio of Aybarinee Campbell Mendez
url: https://aybarineecm.github.io
author: Aybarinee Campbell Mendez
theme: jekyll-theme-minimal
